# Generated by Django 3.2.9 on 2021-11-07 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mox_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='title',
            field=models.CharField(default='No title', max_length=500),
        ),
    ]
